///what directory
scr_SpriteReplace(RedApple,argument0);
scr_SpriteReplace(spr_AltDJ,argument0);
scr_SpriteReplace(GreenApple,argument0);
scr_SpriteReplace(GrnAppleAnim,argument0);
scr_SpriteReplace(GreenAppleCage,argument0);
scr_SpriteReplace(spr_Splapple,argument0);
scr_SpriteReplace(spr_BadSplapple,argument0);
scr_SpriteReplace(spr_Gropple,argument0);
scr_SpriteReplace(SuperGropple,argument0);
scr_SpriteReplace(spr_Gripple,argument0);
scr_SpriteReplace(spr_AppleSwimSealant,argument0);
scr_SpriteReplace(Shaman,argument0);
scr_SpriteReplace(spr_Motewolon,argument0);
scr_SpriteReplace(BlackNoAnim,argument0);
scr_SpriteReplace(RedNoAnim,argument0);
scr_SpriteReplace(BlueNoAnim,argument0);
scr_SpriteReplace(BlueNoAnim2,argument0);
scr_SpriteReplace(Soap,argument0);
scr_SpriteReplace(Leaf,argument0);
scr_SpriteReplace(YellowNoAnim,argument0);
scr_SpriteReplace(LeafNoAnim,argument0);
scr_SpriteReplace(Tex,argument0);
scr_SpriteReplace(TexNoAnim,argument0);
scr_SpriteReplace(Angela,argument0);
scr_SpriteReplace(CyanNoAnim,argument0);
scr_SpriteReplace(Crystal,argument0);
scr_SpriteReplace(WhiteNoAnim,argument0);
scr_SpriteReplace(CL,argument0);
scr_SpriteReplace(PinkNoAnim,argument0);
scr_SpriteReplace(Chroma,argument0);
scr_SpriteReplace(OrangeNoAnim,argument0);

scr_SpriteReplace(spr_DyingApp,argument0);
scr_SpriteReplace(TexFace,argument0);
scr_SpriteReplace(GreenFaceH,argument0);
scr_SpriteReplace(LeafFace,argument0);
scr_SpriteReplace(SoapFace,argument0);
scr_SpriteReplace(AppFace,argument0);
scr_SpriteReplace(AppFace2,argument0);
scr_SpriteReplace(JimFace,argument0);
scr_SpriteReplace(MachFace,argument0);
scr_SpriteReplace(ShamanFace,argument0);
scr_SpriteReplace(CrystalFace,argument0);
scr_SpriteReplace(AngelaFace,argument0);
scr_SpriteReplace(AngelaFace,argument0);
scr_SpriteReplace(GertrudeFace,argument0);
scr_SpriteReplace(ArmoredFace,argument0);
scr_SpriteReplace(CLFace,argument0);
scr_SpriteReplace(ChromaFace,argument0);
scr_SpriteReplace(ChromaFace2,argument0);
scr_SpriteReplace(RiddleFace,argument0);
scr_SpriteReplace(SheekFace,argument0);
scr_SpriteReplace(UDSoapFace,argument0);

if argument0="sprites_apples"
{
scr_SpriteReplace(Mouth,argument0);
scr_SpriteReplace(Eyes,argument0);
scr_SpriteReplace(Eyebrows,argument0);
scr_SpriteReplace(WideEyes,argument0);
scr_SpriteReplace(OtherWear,argument0);
scr_SpriteReplace(Eyelashes,argument0);
scr_SpriteReplace(BlueEyes,argument0);
scr_SpriteReplace(GreenEyes,argument0);
scr_SpriteReplace(RedEyes,argument0);
scr_SpriteReplace(DJumpFace,argument0);
scr_SpriteReplace(BlankFace,argument0);
}
else
{
scr_SpriteReplaceBack(Mouth,argument0);
scr_SpriteReplaceBack(Eyes,argument0);
scr_SpriteReplaceBack(Eyebrows,argument0);
scr_SpriteReplaceBack(WideEyes,argument0);
scr_SpriteReplaceBack(OtherWear,argument0);
scr_SpriteReplaceBack(Eyelashes,argument0);
scr_SpriteReplaceBack(BlueEyes,argument0);
scr_SpriteReplaceBack(GreenEyes,argument0);
scr_SpriteReplaceBack(RedEyes,argument0);
scr_SpriteReplaceBack(DJumpFace,argument0);
scr_SpriteReplaceBack(BlankFace,argument0);
};

scr_SpriteReplace(spr_TinyToaster,argument0);
scr_SpriteReplace(spr_HandyToaster,argument0);
scr_SpriteReplace(spr_HotToaster,argument0);
scr_SpriteReplace(spr_AngryToaster,argument0);
scr_SpriteReplace(spr_MagicToaster,argument0);
scr_SpriteReplace(spr_TinyRoaster,argument0);
scr_SpriteReplace(spr_SmartToaster,argument0);
scr_SpriteReplace(spr_TrickyToaster,argument0);
scr_SpriteReplace(spr_RoasterAim,argument0);
scr_SpriteReplace(spr_ElectricToaster,argument0);
scr_SpriteReplace(spr_ConvertibleToaster1,argument0);
scr_SpriteReplace(spr_ConvertibleToaster2,argument0);
scr_SpriteReplace(spr_RapidToaster,argument0);
scr_SpriteReplace(spr_SlowToaster,argument0);
scr_SpriteReplace(spr_BouncyToaster,argument0);
scr_SpriteReplace(spr_RicochetToaster,argument0);
scr_SpriteReplace(Roaster,argument0);


scr_SpriteReplace(spr_Save,argument0);
scr_SpriteReplace(spr_SaveHappy,argument0);
